#!/bin/bash -e

# See file COPYING distributed with xnatrest for copyright and license.

. common

progname=`basename $0`

if [ $# -ne 1 ]
then
    echo "usage: $progname <XNAT URL>"
    exit 1
fi

xnat_url=`echo "$1" | sed 's+/*$++'`

jsessionid1=`get_jsessionid test1 test1`

echo deleting pubp/s1
curl_ $jsessionid1 \
      -X DELETE \
      ${xnat_url}/data/archive/projects/pubp/subjects/s1?removeFiles=true

echo deleting privp/s1
curl_ $jsessionid1 \
      -X DELETE \
      ${xnat_url}/data/archive/projects/privp/subjects/s1?removeFiles=true

echo
echo exiting normally
echo

exit 0

# eof
